### ISSUE TITLE
Roundtrippability of special strings

### ISSUE THREAD

**Issue by nilshg** [apache/arrow-julia#196]
As discussed on Slack, it would be nice if this would work:

```
julia> using Arrow, DataFrames, ShortStrings

julia> df = DataFrame(stringcol = ShortString7.(["abcde", "fghij"]))
2×1 DataFrame
 Row │ stringcol 
     │ ShortStr… 
─────┼───────────
   1 │ abcde
   2 │ fghij

julia> Arrow.write("test.arrow", df);

julia> DataFrame(Arrow.Table("test.arrow"))
2×1 DataFrame
 Row │ stringcol 
     │ String    
─────┼───────────
   1 │ abcde
   2 │ fghij
```

**Comment by quinnj** [comment]
PR up to add support for InlineStrings round-tripping in arrow: https://github.com/JuliaStrings/InlineStrings.jl/pull/66

**Comment by Moelf** [comment]
So if a Julia user doesn't want to depend on ArrowTypes.jl, they will get back normal String right?

**Comment by quinnj** [comment]
Correct (though it's whether the user has _InlineStrings_ loaded or not, not ArrowTypes):
```julia
julia> t = Arrow.Table("/Users/quinnj/.julia/dev/inlinestrings.arrow")
┌ Warning: unsupported ARROW:extension:name type: "JuliaLang.InlineStrings.InlineString7", arrow type = String
└ @ Arrow ~/.julia/dev/Arrow/src/eltypes.jl:53
Arrow.Table with 3 rows, 1 columns, and schema:
 :x  String
```

**Comment by Moelf** [comment]
yeah... I feel like this kind of support is a bit of rabbit hole, maybe InlineString is special enough to justify.

But in large applications, it might be a food gun that users get different type in schema depending (invisible to user because some other dependency might load it) if another package is loaded or not.

**Comment by ericphanson** [comment]
Btw Legolas.jl will error if `validate=true` and an unknown schema is present, and if a known schema is used it will check the types against it. So Legolas can be used to mitigate the “silent” aspect to some extent.
