### ISSUE TITLE
Transfer repository to apache organization

### ISSUE THREAD

**Issue by quinnj** [apache/arrow-julia#265]
As has been discussed in a few places (slack, arrow-dev mailing list, etc.), we'd like to transfer this repo to the apache organization in our efforts to officially participate in the broader arrow community and project. For the mechanics of the transfer, @kou has very helpfully laid out the plan and TODO items [here](https://lists.apache.org/thread/cr28lsyq1rsxsb810olsj74h7z08zvbg) and we can track the current state of the transfer [here](https://incubator.apache.org/ip-clearance/arrow-julia-library2.html).

There is a request to *NOT* merge any more commits until the transfer is complete; cc active committers: @omus, @jrevels.

To complete the transfer, we just need signed CLAs for the following individuals:

- [x] @jrevels 
- [x] @omus 
- [x] @ericphanson 
- [x] @dmbates 

This list is as computed by @kou for more-than-1-commit since the original donation of the repo to the arrow project. The required CLA can be found [here](https://www.apache.org/licenses/contributor-agreements.html). @jrevels , @omus , @ericphanson, as also noted, if your collective contributions should be viewed under a "corporate" contribution, there's a separate corporate CLA. Happy to chat more if that doesn't make sense or whatever.

Let's do this!

**Comment by jrevels** [comment]
> The required CLA can be found here. @jrevels , @omus , @ericphanson, as also noted, if your collective contributions should be viewed under a "corporate" contribution, there's a separate corporate CLA. 

I don't believe we were thoroughly tracking this, but I think the safest assumption would be to assume that out of our contributions, at least some were made on behalf of Beacon/in the course of Beacon work.

In that case, does it make the most sense to basically just do both? i.e. @jrevels / @omus / @ericphanson all provide individual CLAs, and I also execute a corporate CLA for Beacon?

**Comment by dmbates** [comment]
Do we simply use "arrow" in the notify project box?  The agreement states that we email the signed PDF only to secretary@apache.org Is there any further action that is needed for coordination of the submission?

**Comment by quinnj** [comment]
I think it's fine to use `arrow` or `arrow-julia` as the project box, preferring `arrow`. Yes, you only need to email and then if you'd check your name off hte list above that'd be great.

@jrevels, it's probably safest to do both then.

**Comment by ericphanson** [comment]
I’ve submitted my ICLA, can someone check me off the list? (I don’t have permission)

**Comment by quinnj** [comment]
@jrevels, @omus, @KristofferC; any update?

**Comment by omus** [comment]
I'll submit mine tomorrow

**Comment by quinnj** [comment]
Note that @ericphanson helpfully pointed out that an electronic signature is possible/suffices: https://julialang.slack.com/archives/C02FQ3638CB/p1638988968012400?thread_ts=1638856381.010100&cid=C02FQ3638CB

**Comment by KristofferC** [comment]
I have only one commit that touches the actual source code so according to the discussion about single commit authors in https://lists.apache.org/thread/cr28lsyq1rsxsb810olsj74h7z08zvbg I feel that there should be no requirement to sign anything from my part. There are also things like:

> 5. You represent that each of Your Contributions is Your original creation (see section 7 for submissions on behalf of others). 

which is not true for the PR https://github.com/JuliaData/Arrow.jl/pull/250 since I copy-pasted it from somewhere.

**Comment by kou** [comment]
@KristofferC It makes sense.

**Comment by omus** [comment]
I've submitted my ICLA and have checked myself off the list

**Comment by jrevels** [comment]
I’m in the middle of traveling but will also try to care of this by EOW

**Comment by jrevels** [comment]
Finally got around to this, sorry for the delay - I've submitted both an ICLA for myself and a CCLA for Beacon via the provided instructions. Let me know if anything else is necessary to move forward.

**Comment by quinnj** [comment]
Ok @kou , I think that should be everyone then, assuming we're in agreement to ignore @KristofferC's "administrative" commit. I'm ready to facilitate whatever we need to do next to complete the transfer.

**Comment by kou** [comment]
OK.
Could you remove `@KristofferC` from the list in this description or add a note that "`CLS` isn't needed because ..."?
I'll add a link to this issue to https://incubator.apache.org/ip-clearance/arrow-julia-library2.html .

Did you do the following?

> 2. Remind active committers that they are responsible for
>     ensuring that a Corporate CLA is recorded if such is
>     required to authorize their contributions under their
>     individual CLA.

> And could you also remind
>
>    53	Jacob Quinn
>    16	Jarrett Revels
>    10	Curtis Vogt
>     8	Eric Hanson
>     2	Douglas Bates
>     2	ExpandingMan
>     2	Kristoffer Carlsson
>
> that the TODO item 2.?

I need to record the date when we did it in https://incubator.apache.org/ip-clearance/arrow-julia-library2.html .

**Comment by quinnj** [comment]
> Did you do the following?
> 
> >

Yes, my comment above on Dec 7th was a recommendation to Jarrett that a corporate CLA be signed/provided. I reminded the individual contributors on Dec 6.

I've removed Kristoffer from the list above. Thanks!

**Comment by kou** [comment]
Thanks.

I've filled missing items in https://incubator.apache.org/ip-clearance/arrow-julia-library2.html and started vote: https://lists.apache.org/thread/f9xck9j8qdrhvw363vjl6qkk2g8t4l6b

If we don't receive -1 vote at least 72 hours, the vote can be passed.
I'll ask INFRA to transfer this repository to `apache/arrow-julia` after the vote is passed.

**Comment by jrevels** [comment]
Thanks to both @quinnj and @kou for facilitating this process!

**Comment by kou** [comment]
The vote passed: https://lists.apache.org/thread/byc3voz57qpgr63xdc7bs0q7626n2k0v
I asked INFRA to transfer this repository to `apache/arrow-julia`: https://issues.apache.org/jira/browse/INFRA-22663

@quinnj INFRA may need admin permission to this repository. Please watch https://issues.apache.org/jira/browse/INFRA-22663 and respond to requests from INFRA.

**Comment by quinnj** [comment]
Repo has been transferred
