### ISSUE TITLE
Add GitHub Actions used in this repository to allow list

### ISSUE THREAD

**Issue by kou** [apache/arrow-julia#273]
`apache/*` repositories can use only allowed GitHub Actions in `.github/workflows/`.

We need to ask INFRA to add the following GitHub Actions to allow list:

* `julia-actions/julia-buildpkg@v1.2`
* `julia-actions/julia-processcoverage@v1`
* `julia-actions/julia-buildpkg@latest`
* `julia-actions/julia-docdeploy@latest`
* `juliaregistries/tagbot@v1`

See also: https://issues.apache.org/jira/browse/INFRA-21239

**Comment by kou** [comment]
I've opened INFRA issue for this: https://issues.apache.org/jira/browse/INFRA-22676

**Comment by kou** [comment]
Pinged: https://issues.apache.org/jira/browse/INFRA-22676?focusedCommentId=17469611&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17469611

**Comment by quinnj** [comment]
Any update here? Starting to feel a little discouraging that we're essentially frozen development-wise until this can be cleared. I guess we probably should have done some more prep work before donating to ensure a smoother transition.

**Comment by kou** [comment]
No update. Sorry.
We can use `julia-actions/setup-julia` and `julia-actions/julia-runtest` for now because they are used in `apache/arrow`. How about disable steps that use GitHub Actions except them as workaround?

```diff
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index 4dfd50a..5f675af 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,23 +49,23 @@ jobs:
             ${{ runner.os }}-test-${{ env.cache-name }}-
             ${{ runner.os }}-test-
             ${{ runner.os }}-
-      - uses: julia-actions/julia-buildpkg@v1.2
-        with:
-          project: ${{ matrix.pkg.dir }}
+      # - uses: julia-actions/julia-buildpkg@v1.2
+      #   with:
+      #     project: ${{ matrix.pkg.dir }}
       - uses: julia-actions/julia-runtest@v1
         with:
           project: ${{ matrix.pkg.dir }}
-      - uses: julia-actions/julia-processcoverage@v1
-      - uses: codecov/codecov-action@v1
-        with:
-          file: lcov.info
-  docs:
-    name: Documentation
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - uses: julia-actions/julia-buildpkg@latest
-      - uses: julia-actions/julia-docdeploy@latest
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
+      # - uses: julia-actions/julia-processcoverage@v1
+      # - uses: codecov/codecov-action@v1
+      #   with:
+      #     file: lcov.info
+  # docs:
+  #   name: Documentation
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - uses: julia-actions/julia-buildpkg@latest
+  #     - uses: julia-actions/julia-docdeploy@latest
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #         DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
```

**Comment by kou** [comment]
I add this to Apache Arrow board report that will be referred in ASF board meeting at 2022-01-19.
Draft: https://docs.google.com/document/d/1WQIybbt6xCVoMXztA3rb_N7vrHHrlu9kRcBBmLU8yTs/edit

**Comment by kou** [comment]
CI is runnable again.
