### ISSUE TITLE
Support Tables.partitions when reading "arrow file" format in addition to "stream" format

### ISSUE THREAD

**Issue by complyue** [apache/arrow-julia#293]
I see #23 closed but only *stream* format got supported. 

How about files in "arrow file" format, each with multiple record batches inside?

With released version I get a single `Table` as the result of `Tables.partitions(tbl)` is a `::Tuple{Arrow.Table}`, however the columns there are chunked.

Can we get partition tables with contiguous column arrays via `Tables.partitions`?

---

As for workarounds before that's supported, any public API I can use to obtain contiguous column arrays per each record batches?

**Comment by quinnj** [comment]
PR up: https://github.com/apache/arrow-julia/pull/443
