### ISSUE TITLE
Support InlineStrings

### ISSUE THREAD

**Issue by nilshg** [apache/arrow-julia#304]
It would be good to have similar support for InlineStrings in Arrow as in CSV.jl, ie habe string columns automatically stored and read in as the shortest possible InlineString

**Comment by jariji** [comment]
https://github.com/JuliaStrings/InlineStrings.jl/pull/66

**Comment by Moelf** [comment]
this should be fixed now.

**Comment by nilshg** [comment]
Yes, I didn't realise I had somehow opened this issue twice - closed by https://github.com/apache/arrow-julia/issues/196
