### ISSUE TITLE
filtering DataFrame loaded from feather file triggers `deleteat!` error

### ISSUE THREAD

**Issue by markmbaum** [apache/arrow-julia#324]
I'm loading a table from feather file in a straightforward way
```
df = filename |> Arrow.Table |> DataFrame
```
and attempting to filter it based on the values of one column
```
filter!(row -> row.x < 7, df)
```
but this throws the following error
```

ERROR: MethodError: no method matching deleteat!(::Arrow.Primitive{Float32, Vector{Float32}}, ::Vector{Int64})
Closest candidates are:
  deleteat!(::DataValues.DataValueVector, ::Any) at C:\Users\markm\.julia\packages\DataValues\N7oeL\src\array\datavaluevector.jl:168
  deleteat!(::SubDataFrame, ::Any) at C:\Users\markm\.julia\packages\DataFrames\6xBiG\src\subdataframe\subdataframe.jl:293
  deleteat!(::PooledArrays.PooledVector, ::Any) at C:\Users\markm\.julia\packages\PooledArrays\tQueO\src\PooledArrays.jl:627
  ...
Stacktrace:
 [1] _deleteat!_helper(df::DataFrame, drop::Vector{Int64})
   @ DataFrames C:\Users\markm\.julia\packages\DataFrames\6xBiG\src\dataframe\dataframe.jl:1065
 [2] deleteat!(df::DataFrame, inds::Vector{Int64})
   @ DataFrames C:\Users\markm\.julia\packages\DataFrames\6xBiG\src\dataframe\dataframe.jl:1042
 [3] filter!(f::Function, df::DataFrame)
   @ DataFrames C:\Users\markm\.julia\packages\DataFrames\6xBiG\src\abstractdataframe\abstractdataframe.jl:1211
 [4] top-level scope
   @ REPL[6]:1
```
The problem can be fixed by reallocating the columns
```
df = mapcols(Vector, df)
```
But it seems like filtering (and potentially other operations) should work on a data frame after loading from feather without further manipulation. Not a huge deal and perhaps this is an issue better directed to `DataFrames.jl`, but I thought worth pointing out.

Also my versions are
```
Arrow v2.3.0
DataFrames v1.3.4
```

**Comment by quinnj** [comment]
Thanks for reporting the issue @markmbaum; yeah, we've tried to communicate (via docs and otherwise) that an `Arrow.Table` (and its columns) are immutable by nature of the format, but I recognize that doesn't always translate to users understanding that things like `filter!` won't work (as opposed to `filter` that doesn't try to mutate underlying columns).

@bkamins, any ideas on how we could make this clearer for users? Maybe we overload common mutating array functions with helpful error messages?

**Comment by markmbaum** [comment]
A more helpful error would be nice. I think people are likely to run in to this confusion. For example you can load the data frame as above, check that `typeof(df) === DataFrame`, and get the error on `filter!` even though
```
filter!(row -> row.x < 7, copy(df))
```
will work just fine, even if the copy useless.

**Comment by bkamins** [comment]
@quinnj - I would propose to resolve it in Arrow.jl. I.e. add a method `deleteat!` for `::Arrow.Primitive` (or whatever type makes sense) that throws an informative error. The point is that in this way any `filter!` operation (or other operation trying to drop elements) will give a good error message (not only in DataFrames.jl but in any package that uses `Arrow.Table`).

**Comment by quinnj** [comment]
Sounds good; PR up: https://github.com/apache/arrow-julia/pull/341
