### ISSUE TITLE
Install Registrator.jl github app

### ISSUE THREAD

**Issue by ericphanson** [apache/arrow-julia#348]
Can we install the Julia Registrator github app on this repository? https://github.com/JuliaRegistries/Registrator.jl#install-registrator
<img width="654" alt="Screen Shot 2022-10-28 at 2 22 11 PM" src="https://user-images.githubusercontent.com/5846501/198585934-972f8963-84c1-429a-acea-deca5ba872c6.png">

I can request it to be installed, but I guess someone will have to approve it. I have not requested it yet in case it is a breach of etiquette and there is a different process to be followed.

Why?

This enables us to easily register packages in Julia's package registry. It only requires minimal read-only permissions. This is the standard workflow for registering Julia packages.

**Comment by quinnj** [comment]
Yes, this would be great; @kou can you help us know what is required here? This is standard procedure for ensuring consistent, predictable releases with the General registry.

**Comment by kou** [comment]
Could you open a new issue for this on https://issues.apache.org/jira/projects/INFRA/issues/ like https://issues.apache.org/jira/browse/INFRA-22663 ?

Here are field values to be used:

* Project (in main fields): INFRA
* Issue Type: Task
* Project (in sub fields): Arrow
* Component/s: GitHub

**Comment by ericphanson** [comment]
I have filed the Jira issue here: https://issues.apache.org/jira/projects/INFRA/issues/INFRA-23959

**Comment by ericphanson** [comment]
This was done a few hours after I filed the request!
