### ISSUE TITLE
PooledArray are incorrectly saved

### ISSUE THREAD

**Issue by TanookiToad** [apache/arrow-julia#364]
If a float-type element in ```PooledVector{Real, UInt32, Vector{UInt32}}``` is replaced by an integer, Arrow will incorrectly save this value.

```
using Arrow, DataFrames, PooledArrays

df = DataFrame(x = PooledArray(Vector{Real}([1.0])))
df[1, 1] = 2
Arrow.write("test.arrow", df)
Arrow.Table("test.arrow") |> DataFrame
```

The above code incorrectly saves 2 as 1.0e-323.

```
1×1 DataFrame
 Row │ x        
     │ Float64
─────┼──────────
   1 │ 1.0e-323
```

**Comment by TanookiToad** [comment]
Seems like it's caused by the wrong serialization of non-concrete type. Similar to https://github.com/apache/arrow-julia/issues/232. Maybe we could also add a check to the type of PooledArray elements?

**Comment by jrevels** [comment]
Oof, this is quite a bad bug. Good catch.

---

A bit of an aside, but FWIW, I wouldn't be opposed to Arrow.jl defaulting to an error when asked to serialize any container with nonconcrete eltype (basically, extend https://github.com/apache/arrow-julia/pull/305 to all containers)

Bugs that can result in silent data loss/corruption are amongst the most insidious type of bug that a package like Arrow.jl can possibly have, I'd much rather limit functionality to avoid them

**Comment by quinnj** [comment]
Yeah, this is a pretty bummer bug. PR up: https://github.com/apache/arrow-julia/pull/365.

Yeah, I think I agree that we probably shouldn't have tried to be so loose about turning abstractly typed column vectors into promoted union/concrete types (and thus exposing ourselves to this bug), but it is a pretty convenient usability thing and not super easy to deal w/ if you're new to Julia/data in julia. We can perhaps consider alternative approaches for a 3.0 release.
