### ISSUE TITLE
Does this pkg provide the plasma In-Memory Object Store?

### ISSUE THREAD

**Issue by mkschulze** [apache/arrow-julia#37]
Hello,

just wondering if it's in like in the pyarrow package.

https://arrow.apache.org/docs/python/plasma.html

Thx!

**Comment by quinnj** [comment]
Currently there's no interface for interacting with a plasma store. From a quick look at what plasma is, it sounds like it would be pretty easy to make a generic Julia client that could put/get objects. Probably more work is supporting arbitrary Julia object sterilization in Arrow.jl. I'm not familiar with how pyarrow does their object serialization, but perhaps we could do something similar. My hesitation is knowing that totally generic serialization in Julia can be a lot of work; but maybe there are simple cases we could support.

**Comment by mkschulze** [comment]
Maybe this project can serve as some inspiration: https://github.com/russellromney/brain-plasma

It wraps the plasma store and adds a namespace functionality.

**Comment by quinnj** [comment]
My understanding is that plasma is no longer maintained and isn't recommended any more
