### ISSUE TITLE
github releases not in sync 

### ISSUE THREAD

**Issue by CarloLucibello** [apache/arrow-julia#370]
Last tagged version is v2.4.1, while github releases are stuck to v2.2.1.
Something wrong with tagbot here?

**Comment by ericphanson** [comment]
I am not 100% sure but I think maybe TagBot relies on registration via Registrator, and these last few releases were made by manual PRs. We now have Registrator installed (#348), so perhaps this will be fixed in future releases. (…or maybe it could be something else! I am just guessing).

**Comment by quinnj** [comment]
There was the issue at one point where TagBot was mad because there was already a v2.0.0 tag (from Arrowtypes), so it couldn't make a v2.0.0 tag for Arrow.jl.

**Comment by ericphanson** [comment]
https://github.com/JuliaRegistries/TagBot/pull/252 should help with that

**Comment by ericphanson** [comment]
Tagbot did run this time but we are hitting https://github.com/JuliaRegistries/TagBot/issues/242

**Comment by quinnj** [comment]
TagBot is now working correctly, even though we are still sorting out the right documentation updates.
