### ISSUE TITLE
Make recursive iteration to get dictionaries more defensive for interop

### ISSUE THREAD

**Issue by okartal** [apache/arrow-julia#375]
The problem I have encountered is due to this for loop:

https://github.com/apache/arrow-julia/blob/528c3ba9eaa38b7e9c1ff3d4c998f5b304ec64cf/src/table.jl#L387

It assumes that `field.children` is an iterable and, to my understanding, this assumption is usually warranted as for the last elements, when the leaves of the tree are reached, `field.children` is `Arrow.Flatbuf.Field[]`. However, we have observed that when Arrow files are written in C# `field.children === nothing` and trying to iterate throws an error. I can share an example file.

I could fix this in my `dev`ed, local Arrow.jl by simply conditioning the for loop:

```julia
if field.children !== nothing
    for child in field.children
        getdictionaries!(dictencoded, child)
    end
end
```

I am not sure if this is the right fix but I am opening this issue here because I am more familiar with the Arrow implementation in Julia and I think it is reasonable to be more defensive. But, as reading the same data works once the file is imported-exported with Python/pyarrow, my guess is that it is the C# implementation of Arrow that is doing something fishy here. Maybe this can also be fixed at the site where Julia produces the `nothing` when translating the Arrow types?

**Comment by quinnj** [comment]
that looks like a good fix to me; if you make a PR, that'd be great. If you have an example arrow file that exhibits the problem that we can use to test it with, even better.

**Comment by okartal** [comment]
@quinnj I opened a PR now and I can definitely share a file beginning of next week. Thanks a lot for this great project!
