### ISSUE TITLE
Release ArrowTypes@2.0.2

### ISSUE THREAD

**Issue by mattBrzezinski** [apache/arrow-julia#376]
A place for @kou to post the progress of releasing `ArrowTypes@2.0.2`, based off [this](https://github.com/apache/arrow-julia/commit/94ee070adcf6d4a7ed3108561ee014702e75b835#commitcomment-96003882) comment.

**Comment by kou** [comment]
@quinnj Should we release only `ArrowTypes`? (We don't release `Arrow`?)
Our established release script doesn't assume this case. (`ArrowTypes` is only released.)
Can we also release `Arrow@2.4.2` or something?

**Comment by quinnj** [comment]
Yeah, let's do an Arrow 2.4.2 release as well. https://github.com/apache/arrow-julia/pull/377

**Comment by kou** [comment]
Start voting: https://lists.apache.org/thread/wwctxdr1cqd940z8j7rvfbncsxkyp59h

**Comment by kou** [comment]
Passed: https://lists.apache.org/thread/c4ggkv4vy5kctn2vtgpgg3195t6sn9g1

Published: https://dist.apache.org/repos/dist/release/arrow/arrow-julia-2.4.2/

Could someone update the Julia General registry?

**Comment by ericphanson** [comment]
Registry updated! TagBot is currently malfunctioning so we don’t have a github “release” (#370) but that isn’t required (it’s customary and helps users see the latest release but the package manager doesn’t use it in any way).

**Comment by kou** [comment]
Thanks!
