### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by ericphanson** [apache/arrow-julia#387]
It would be really nice to get a release with the bugfix https://github.com/apache/arrow-julia/pull/385. We currently have CI failures downstream (e.g. https://github.com/beacon-biosignals/Lighthouse.jl/pull/101) which blocks PRs being merged.

**Comment by quinnj** [comment]
I agree. I went ahead and [bumped the version](https://github.com/apache/arrow-julia/commit/8c0cc4498801758064bd72ffa2fa6460cfc51fdc); @kou, can you kick off the release process please?

**Comment by kou** [comment]
Sure. I'll do.

**Comment by kou** [comment]
Vote thread: https://lists.apache.org/thread/lq7ss1js3bglb0gwy5tmvozbpgwrycyh

**Comment by kou** [comment]
Carried: https://lists.apache.org/thread/kf7s1zoqx9wgzwhkdvs2418k20ds10t8

I've published 2.4.3 archive without tagging.
Could you update the Julia General registry and add a tag for 2.4.3?

**Comment by ericphanson** [comment]
looks like tagbot worked this time! both done. Thanks @kou!

**Comment by kou** [comment]
Great!

**Comment by quinnj** [comment]
Yay, so great ot have TagBot working.
