### ISSUE TITLE
Incorrect syntax in ArrowTypes code

### ISSUE THREAD

**Issue by ericphanson** [apache/arrow-julia#453]
https://github.com/apache/arrow-julia/blob/8aed96998ace1010580a74d03222770140acd579/src/ArrowTypes/src/ArrowTypes.jl#L122-L123

I think this should be
```julia
 arrowmetadata(::Type{Union{T,Missing}}) where {T} = arrowmetadata(T)
 arrowmetadata(::Type{Union{T,Nothing}}) where {T} = arrowmetadata(T) 
```

**Comment by baumgold** [comment]
@ericphanson - good catch.  #453 for the fix.  Apologies for the inconvenience.
