### ISSUE TITLE
Use https://arrow.apache.org/julia/ as the official Website URL

### ISSUE THREAD

**Issue by kou** [apache/arrow-julia#470]
I think that we need to update at least the followings:
* `.asf.yaml`
* `README.md`
* `docs/make.jl`

**Comment by Moelf** [comment]
@quinnj

**Comment by kou** [comment]
It seems that https://arrow.apache.org/julia/dev/ is generated from `main`: https://github.com/apache/arrow-julia/commit/95efe954784062a115c2a5af15f5c4dbde3fe6f3

What does "docs online is still so out dated" mean?

**Comment by Moelf** [comment]
>What does "docs online is still so out dated" mean?

that was from Aug 30, I must have mistaken when I ping-ed quinn again since I see this issue still open.

We can close this now?

**Comment by kou** [comment]
No.

We need to update URLs at least in the followings as I wrote in the description:

>     * `.asf.yaml`
> 
>     * `README.md`
> 
>     * `docs/make.jl`

For example: https://github.com/apache/arrow-julia/blob/42a46f5087ffb6a1f4e03cfe5d2236b646a6656f/.asf.yaml#L28

**Comment by Moelf** [comment]
do you not have commit right to do that?

**Comment by kou** [comment]
I have commit right. So I can review and merge a PR for this.
But no one seems interested in this.
I've opened a PR: #490
