### ISSUE TITLE
`snappy_jll v1.2.0` lead to Arrow_jll failed to build

### ISSUE THREAD

**Issue by kongdd** [apache/arrow-julia#505]
`snappy_jll@1.1.10` works normally. But the latest released version broke Arrow_jll and Arrow.jl.

**Comment by visr** [comment]
Arrow.jl is a Julia implementation of the Arrow format, and does not use Arrow_jll, so this issue can be closed.

**Comment by Moelf** [comment]
What is using Arrow_jll -- do we have a wrapper ?

**Comment by kongdd** [comment]
> Arrow.jl is a Julia implementation of the Arrow format, and does not use Arrow_jll, so this issue can be closed.

closed

**Comment by visr** [comment]
No direct wrapper yet. We built it for GDAL to be able to read geospatial data based on Arrow and Parquet; GeoArrow and GeoParquet.
